defaults:

  # Train Script
  logdir: /dev/null
  load_logdir: none
  seed: 0
  task: dmc_walker_walk
  envs: 1
  envs_parallel: none
  render_size: [64, 64]
  dmc_camera: -1
  camera: corner
  atari_grayscale: True
  time_limit: 0
  action_repeat: 1
  steps: 1e8
  log_every: 1e4
  eval_every: 1e4
  eval_eps: 1
  prefill: 10000
  pretrain: 100
  mae_pretrain: 5000  # mae
  train_every: 5
  train_mae_every: 5  # mae
  train_steps: 1
  train_mae_steps: 1  # mae
  expl_until: 0
  replay: {capacity: 1e6, ongoing: False, minlen: 50, maxlen: 50, prioritize_ends: True}
  dataset: {batch: 16, length: 50}
  mae_dataset: {batch: 32, length: 32}
  log_keys_video: ['image']
  log_keys_sum: '^$'
  log_keys_mean: '^$'
  log_keys_max: '^$'
  precision: 16
  jit: True

  # Agent
  clip_rewards: identity
  expl_behavior: greedy
  expl_noise: 0.0
  eval_noise: 0.0
  eval_state_mean: False

  # Fine-tuning parameters
  load_modules: [mae_encoder, mae_decoder, vit_encoder, vit_decoder, af_rssm]
  enc_lr_type: no_pretrain
  concat_embed: False

  # Intrinsic bonus parameters
  k: 16
  beta: 1.0
  intr_seq_length: 5
  intr_reward_norm: {momentum: 0.99, scale: 1.0, eps: 1e-8}
  queue_size: 4096 
  queue_dim: 128

  # MAE
  mask_ratio: 0.75
  mae: { img_size: 64, patch_size: 8, embed_dim: 256, depth: 4, num_heads: 4, decoder_embed_dim: 256, decoder_depth: 3, decoder_num_heads: 4, reward_pred: False, early_conv: True, in_chans: 3 }
  wm_flat_vit: { img_size: 8, patch_size: 1, embed_dim: 128, depth: 2, num_heads: 4, decoder_embed_dim: 128, decoder_depth: 2, decoder_num_heads: 4, in_chans: 256 }

  # World Model
  grad_heads: [reward]
  pred_discount: False
  rssm: {action_free: False, ensemble: 1, hidden: 1024, deter: 1024, stoch: 32, discrete: 32, act: elu, norm: none, std_act: sigmoid2, min_std: 0.1}
  af_rssm: {action_free: True, ensemble: 1, hidden: 1024, deter: 1024, stoch: 32, discrete: 32, act: elu, norm: none, std_act: sigmoid2, min_std: 0.1}
  reward_head: {layers: 4, units: 400, act: elu, norm: none, dist: mse}
  discount_head: {layers: 4, units: 400, act: elu, norm: none, dist: binary}
  loss_scales: {af_kl: 0.0, kl: 1.0, feature: 1.0, reward: 1.0, action: 1.0, discount: 1.0, proprio: 1.0}
  kl: {free: 0.0, forward: False, balance: 0.8, free_avg: True}
  model_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100, wd: 1e-6}
  enc_model_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100, wd: 1e-6}  # apv.lr: 3e-4
  mae_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100.0, wd: 1e-6, warmup: 2500}

  # Actor Critic
  actor: {layers: 4, units: 400, act: elu, norm: none, dist: auto, min_std: 0.1}
  critic: {layers: 4, units: 400, act: elu, norm: none, dist: mse}
  actor_opt: {opt: adam, lr: 8e-5, eps: 1e-5, clip: 100, wd: 1e-6}
  critic_opt: {opt: adam, lr: 8e-5, eps: 1e-5, clip: 100, wd: 1e-6}
  discount: 0.99
  discount_lambda: 0.95
  imag_horizon: 15
  actor_grad: auto
  actor_grad_mix: 0.1
  actor_ent: 1e-4
  slow_target: True
  slow_target_update: 100
  slow_target_fraction: 1
  slow_baseline: True
  reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}

  # Exploration
  expl_intr_scale: 1.0
  expl_extr_scale: 0.0
  expl_opt: {opt: adam, lr: 3e-4, eps: 1e-5, clip: 100, wd: 1e-6}
  expl_head: {layers: 4, units: 400, act: elu, norm: none, dist: mse}
  expl_reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}
  disag_target: stoch
  disag_log: False
  disag_models: 10
  disag_offset: 1
  disag_action_cond: True
  expl_model_loss: kl


metaworld:

  task: metaworld_door_open
  dataset: {batch: 50, length: 50}
  time_limit: 500
  action_repeat: 1
  eval_eps: 10
  prefill: 5000
  camera: corner
  steps: 256000
  concat_embed: False
  enc_lr_type: no_pretrain
  beta: 1.0


dmc_vision:

  task: dmc_walker_walk
  action_repeat: 2
  prefill: 1000
  eval_every: 5e3
  log_every: 1e3
  eval_eps: 5
  replay.prioritize_ends: False
  kl.free: 1.0
  steps: 502000  # 502000
  concat_embed: True
  enc_lr_type: none
  beta: 0.1
  model_opt.lr: 3e-4
  enc_model_opt.lr: 3e-4
  actor_opt.lr: 8e-5
  critic_opt.lr: 8e-5

rlbench:
  task: rlbench_reach_target
  time_limit: 200
  action_repeat: 2
  eval_every: 5e3
  log_every: 1e3
  eval_eps: 10
  steps: 502000
  model_opt.lr: 3e-4
  actor_opt.lr: 1e-4
  critic_opt.lr: 1e-4
  concat_embed: False
  enc_lr_type: no_pretrain  #
  dataset: {batch: 50, length: 50}
  reward_norm.momentum: 0.99
  # episodic
  pred_discount: True
  replay.minlen: 1
  grad_heads: [reward, discount]
  # rlbench-specific async env
  envs_parallel: process